# Generated by Django 5.1.2 on 2024-10-21 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0003_certificatetemplate_qrcodecustomization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="qr_customization",
        ),
        migrations.RemoveField(
            model_name="certificatetemplate",
            name="template_file",
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="certificate_templates"
            ),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="body_font_size",
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="font",
            field=models.CharField(default="Helvetica", max_length=50),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="qr_code_position",
            field=models.CharField(
                choices=[
                    ("top_left", "Top Left"),
                    ("top_right", "Top Right"),
                    ("bottom_left", "Bottom Left"),
                    ("bottom_right", "Bottom Right"),
                ],
                default="bottom_right",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="text_color",
            field=models.CharField(default="#000000", max_length=7),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="title_font_size",
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="certifications.certificatetemplate",
            ),
        ),
    ]
