# Generated by Django 5.1.2 on 2024-10-21 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0004_remove_certificate_qr_customization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="csv_uploads")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SampleCSV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="sample_csv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="certificates",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="certificatetemplate",
            name="body_font_size",
        ),
        migrations.RemoveField(
            model_name="certificatetemplate",
            name="font",
        ),
        migrations.RemoveField(
            model_name="certificatetemplate",
            name="text_color",
        ),
        migrations.RemoveField(
            model_name="certificatetemplate",
            name="title_font_size",
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(max_length=100, verbose_name="Name of Student"),
                ),
                (
                    "student_id",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Student Identification Number",
                    ),
                ),
                (
                    "programm",
                    models.CharField(max_length=100, verbose_name="Programme studied"),
                ),
                (
                    "degree_obtained",
                    models.CharField(max_length=100, verbose_name="Degree Obtained"),
                ),
                (
                    "issue_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Certification Issued Date",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes"),
                ),
                ("verification_status", models.BooleanField(default=False)),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certifications.issuer",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="certifications.certificatetemplate",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
