# Generated by Django 5.1.2 on 2024-10-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0006_remove_issuer_url_remove_student_qr_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="qr_code_link",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="QR Code Link"
            ),
        ),
    ]
