# Generated by Django 5.1.2 on 2024-10-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0007_student_qr_code_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="qr_code_link",
            field=models.URLField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="QR Code Link",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.IntegerField(
                unique=True, verbose_name="Student Identification Number"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={
                ("student_name", "student_id", "programm", "degree_obtained", "issuer")
            },
        ),
    ]
