# Generated by Django 4.0.6 on 2024-10-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0008_alter_student_qr_code_link_alter_student_student_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvupload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='csvupload',
            name='error_log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='failed_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='successful_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='total_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='file',
            field=models.FileField(upload_to='uploads/csv/'),
        ),
    ]
