# Generated by Django 4.0.6 on 2024-10-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0009_alter_csvupload_options_csvupload_error_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuer',
            name='name_ar',
        ),
    ]
