# Generated by Django 4.0.6 on 2024-10-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0010_remove_issuer_name_ar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='student',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Naissance'),
        ),
        migrations.AddField(
            model_name='student',
            name='filiere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='student',
            name='lieu_de_naissance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de Naissance'),
        ),
        migrations.AddField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='student',
            name='mention',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mention'),
        ),
        migrations.AddField(
            model_name='student',
            name='noms_et_prenoms',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Noms et Prénoms'),
        ),
        migrations.AddField(
            model_name='student',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro'),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='student',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='student',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de Délivrance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='qr_code_link',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='Lien QR Code'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('noms_et_prenoms', 'matricule', 'filiere', 'session')},
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree_obtained',
        ),
        migrations.RemoveField(
            model_name='student',
            name='programm',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
    ]
